version: 0.2

phases:
  install:
    commands:
      - docker info || exit 0
      - docker compose version || exit 0
      - yarn install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - npx playwright test
artifacts:
  files:
    - ./test-results