name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -l
      - run: cd __tests__/playwright/
      - run: ls -l
      - run: docker compose version
      - run: docker compose up
